{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    app.kubernetes.io/name: novaflow-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: novaflow-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: novaflow-operator
    spec:
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
{{- end }}
